stages:
  - test
  - build
  - tag

pre-commit framework:
  image: python:3.7
  stage: test
  cache:
    key: pip-cache
    paths:
      - .cache/pip
      - .pytest_cache
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  before_script:
    - pip install -U pre-commit
  script:
    - pre-commit run --all-files

.docker:
  image: docker:stable
  stage: build
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  extends: .docker
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build
      --cache-from $CI_REGISTRY_IMAGE:latest
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - if [[ "$CI_COMMIT_REF_SLUG" -eq master ]]; then docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG $CI_REGISTRY_IMAGE:master-$CI_COMMIT_SHORT_SHA; fi
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

tag latest:
  extends: .docker
  stage: tag
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master
