repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v2.1.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.7.7"
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-bugbear"]
  - repo: https://github.com/pycqa/isort
    rev: "5.10.1"
    hooks:
      - id: isort
  - repo: https://github.com/python/black
    rev: "21.8b0"
    hooks:
      - id: black
