[tool.poetry]
name = "diba2ynab"
version = "0.1.0"
description = ""
authors = ["Jan Willhaus <mail@janwillhaus.de>"]

[tool.poetry.dependencies]
python = "^3.7"
fints = "^2.1"
pyyaml = "^5.1"
ynab-python = {git = "https://github.com/deanmcgregor/ynab-python.git"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
