name: docker-build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate tag(s) from GitHub ref
        id: docker-tag
        uses: yuya-takeyama/docker-tag-from-github-ref-action@v1

      - name: Log in to ghcr.io registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get image name from lowercased repo name
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" | tee -a ${GITHUB_ENV}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/${{ env.IMAGE_NAME }}:${{ steps.docker-tag.outputs.tag }}
          push: true
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
